# Generated by Django 4.0.1 on 2023-03-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('mobile', models.IntegerField()),
                ('city', models.CharField(max_length=64)),
                ('deposit_amt', models.IntegerField()),
                ('balance_amt', models.IntegerField()),
            ],
        ),
    ]
